export type CountryLocale = "en" | "ro";

type CountryData = {
	code: string;
	en: string;
	ro: string;
};

export type CountryOption = CountryData & {
	flagSrc: string;
	keywords: string[];
};

const COUNTRIES: CountryData[] = [
	{ code: "AF", en: "Afghanistan", ro: "Afganistan" },
	{ code: "AL", en: "Albania", ro: "Albania" },
	{ code: "DZ", en: "Algeria", ro: "Algeria" },
	{ code: "AD", en: "Andorra", ro: "Andorra" },
	{ code: "AO", en: "Angola", ro: "Angola" },
	{ code: "AG", en: "Antigua and Barbuda", ro: "Antigua și Barbuda" },
	{ code: "AR", en: "Argentina", ro: "Argentina" },
	{ code: "AM", en: "Armenia", ro: "Armenia" },
	{ code: "AU", en: "Australia", ro: "Australia" },
	{ code: "AT", en: "Austria", ro: "Austria" },
	{ code: "AZ", en: "Azerbaijan", ro: "Azerbaidjan" },
	{ code: "BS", en: "Bahamas", ro: "Bahamas" },
	{ code: "BH", en: "Bahrain", ro: "Bahrain" },
	{ code: "BD", en: "Bangladesh", ro: "Bangladesh" },
	{ code: "BB", en: "Barbados", ro: "Barbados" },
	{ code: "BY", en: "Belarus", ro: "Belarus" },
	{ code: "BE", en: "Belgium", ro: "Belgia" },
	{ code: "BZ", en: "Belize", ro: "Belize" },
	{ code: "BJ", en: "Benin", ro: "Benin" },
	{ code: "BT", en: "Bhutan", ro: "Bhutan" },
	{ code: "BO", en: "Bolivia, Plurinational State of", ro: "Bolivia" },
	{ code: "BA", en: "Bosnia and Herzegovina", ro: "Bosnia și Herțegovina" },
	{ code: "BW", en: "Botswana", ro: "Botswana" },
	{ code: "BR", en: "Brazil", ro: "Brazilia" },
	{ code: "BN", en: "Brunei Darussalam", ro: "Brunei" },
	{ code: "BG", en: "Bulgaria", ro: "Bulgaria" },
	{ code: "BF", en: "Burkina Faso", ro: "Burkina Faso" },
	{ code: "BI", en: "Burundi", ro: "Burundi" },
	{ code: "KH", en: "Cambodia", ro: "Cambodgia" },
	{ code: "CM", en: "Cameroon", ro: "Camerun" },
	{ code: "CA", en: "Canada", ro: "Canada" },
	{ code: "CV", en: "Cabo Verde", ro: "Republica Capului Verde" },
	{ code: "CF", en: "Central African Republic", ro: "Republica Centrafricană" },
	{ code: "TD", en: "Chad", ro: "Ciad" },
	{ code: "CL", en: "Chile", ro: "Chile" },
	{ code: "CN", en: "China", ro: "Republica Populară Chineză" },
	{ code: "CO", en: "Colombia", ro: "Columbia" },
	{ code: "KM", en: "Comoros", ro: "Comore" },
	{ code: "CG", en: "Congo", ro: "Congo" },
	{ code: "CD", en: "Congo, Democratic Republic of the", ro: "Republica Democrată Congo" },
	{ code: "CR", en: "Costa Rica", ro: "Costa Rica" },
	{ code: "CI", en: "Côte d'Ivoire", ro: "Coasta de Fildeș" },
	{ code: "HR", en: "Croatia", ro: "Croația" },
	{ code: "CU", en: "Cuba", ro: "Cuba" },
	{ code: "CY", en: "Cyprus", ro: "Cipru" },
	{ code: "CZ", en: "Czechia", ro: "Cehia" },
	{ code: "DK", en: "Denmark", ro: "Danemarca" },
	{ code: "DJ", en: "Djibouti", ro: "Djibouti" },
	{ code: "DM", en: "Dominica", ro: "Dominica" },
	{ code: "DO", en: "Dominican Republic", ro: "Republica Dominicană" },
	{ code: "EC", en: "Ecuador", ro: "Ecuador" },
	{ code: "EG", en: "Egypt", ro: "Egipt" },
	{ code: "SV", en: "El Salvador", ro: "El Salvador" },
	{ code: "GQ", en: "Equatorial Guinea", ro: "Guineea Ecuatorială" },
	{ code: "ER", en: "Eritrea", ro: "Eritreea" },
	{ code: "EE", en: "Estonia", ro: "Estonia" },
	{ code: "ET", en: "Ethiopia", ro: "Etiopia" },
	{ code: "FJ", en: "Fiji", ro: "Fiji" },
	{ code: "FI", en: "Finland", ro: "Finlanda" },
	{ code: "FR", en: "France", ro: "Franța" },
	{ code: "GA", en: "Gabon", ro: "Gabon" },
	{ code: "GM", en: "Gambia", ro: "Gambia" },
	{ code: "GE", en: "Georgia", ro: "Georgia" },
	{ code: "DE", en: "Germany", ro: "Germania" },
	{ code: "GH", en: "Ghana", ro: "Ghana" },
	{ code: "GR", en: "Greece", ro: "Grecia" },
	{ code: "GD", en: "Grenada", ro: "Grenada" },
	{ code: "GT", en: "Guatemala", ro: "Guatemala" },
	{ code: "GN", en: "Guinea", ro: "Guineea" },
	{ code: "GW", en: "Guinea-Bissau", ro: "Guineea-Bissau" },
	{ code: "GY", en: "Guyana", ro: "Guyana" },
	{ code: "HT", en: "Haiti", ro: "Haiti" },
	{ code: "HN", en: "Honduras", ro: "Honduras" },
	{ code: "HU", en: "Hungary", ro: "Ungaria" },
	{ code: "IS", en: "Iceland", ro: "Islanda" },
	{ code: "IN", en: "India", ro: "India" },
	{ code: "ID", en: "Indonesia", ro: "Indonezia" },
	{ code: "IR", en: "Iran, Islamic Republic of", ro: "Iran" },
	{ code: "IQ", en: "Iraq", ro: "Irak" },
	{ code: "IE", en: "Ireland", ro: "Republica Irlanda" },
	{ code: "IL", en: "Israel", ro: "Israel" },
	{ code: "IT", en: "Italy", ro: "Italia" },
	{ code: "JM", en: "Jamaica", ro: "Jamaica" },
	{ code: "JP", en: "Japan", ro: "Japonia" },
	{ code: "JO", en: "Jordan", ro: "Iordania" },
	{ code: "KZ", en: "Kazakhstan", ro: "Kazahstan" },
	{ code: "KE", en: "Kenya", ro: "Kenya" },
	{ code: "KI", en: "Kiribati", ro: "Kiribati" },
	{ code: "KP", en: "Korea, Democratic People's Republic of", ro: "Coreea de Nord" },
	{ code: "KR", en: "Korea, Republic of", ro: "Coreea de Sud" },
	{ code: "KW", en: "Kuwait", ro: "Kuweit" },
	{ code: "KG", en: "Kyrgyzstan", ro: "Kârgâzstan" },
	{ code: "LA", en: "Lao People's Democratic Republic", ro: "Laos" },
	{ code: "LV", en: "Latvia", ro: "Letonia" },
	{ code: "LB", en: "Lebanon", ro: "Liban" },
	{ code: "LS", en: "Lesotho", ro: "Lesotho" },
	{ code: "LR", en: "Liberia", ro: "Liberia" },
	{ code: "LY", en: "Libya", ro: "Libia" },
	{ code: "LI", en: "Liechtenstein", ro: "Liechtenstein" },
	{ code: "LT", en: "Lithuania", ro: "Lituania" },
	{ code: "LU", en: "Luxembourg", ro: "Luxemburg" },
	{ code: "MK", en: "North Macedonia", ro: "Macedonia de Nord" },
	{ code: "MG", en: "Madagascar", ro: "Madagascar" },
	{ code: "MW", en: "Malawi", ro: "Malawi" },
	{ code: "MY", en: "Malaysia", ro: "Malaezia" },
	{ code: "MV", en: "Maldives", ro: "Maldive" },
	{ code: "ML", en: "Mali", ro: "Mali" },
	{ code: "MT", en: "Malta", ro: "Malta" },
	{ code: "MH", en: "Marshall Islands", ro: "Insulele Marshall" },
	{ code: "MR", en: "Mauritania", ro: "Mauritania" },
	{ code: "MU", en: "Mauritius", ro: "Mauritius" },
	{ code: "MX", en: "Mexico", ro: "Mexic" },
	{ code: "FM", en: "Micronesia, Federated States of", ro: "Micronezia" },
	{ code: "MA", en: "Morocco", ro: "Maroc" },
	{ code: "MD", en: "Moldova, Republic of", ro: "Republica Moldova" },
	{ code: "MC", en: "Monaco", ro: "Monaco" },
	{ code: "MN", en: "Mongolia", ro: "Mongolia" },
	{ code: "ME", en: "Montenegro", ro: "Muntenegru" },
	{ code: "MZ", en: "Mozambique", ro: "Mozambic" },
	{ code: "MM", en: "Myanmar", ro: "Myanmar" },
	{ code: "NA", en: "Namibia", ro: "Namibia" },
	{ code: "NR", en: "Nauru", ro: "Nauru" },
	{ code: "NP", en: "Nepal", ro: "Nepal" },
	{ code: "NL", en: "Netherlands", ro: "Țările de Jos" },
	{ code: "NZ", en: "New Zealand", ro: "Noua Zeelandă" },
	{ code: "NI", en: "Nicaragua", ro: "Nicaragua" },
	{ code: "NE", en: "Niger", ro: "Niger" },
	{ code: "NG", en: "Nigeria", ro: "Nigeria" },
	{ code: "NO", en: "Norway", ro: "Norvegia" },
	{ code: "OM", en: "Oman", ro: "Oman" },
	{ code: "PK", en: "Pakistan", ro: "Pakistan" },
	{ code: "PW", en: "Palau", ro: "Palau" },
	{ code: "PA", en: "Panama", ro: "Panama" },
	{ code: "PG", en: "Papua New Guinea", ro: "Papua Noua Guinee" },
	{ code: "PY", en: "Paraguay", ro: "Paraguay" },
	{ code: "PE", en: "Peru", ro: "Peru" },
	{ code: "PH", en: "Philippines", ro: "Filipine" },
	{ code: "PL", en: "Poland", ro: "Polonia" },
	{ code: "PT", en: "Portugal", ro: "Portugalia" },
	{ code: "QA", en: "Qatar", ro: "Qatar" },
	{ code: "RO", en: "Romania", ro: "România" },
	{ code: "RU", en: "Russian Federation", ro: "Rusia" },
	{ code: "RW", en: "Rwanda", ro: "Rwanda" },
	{ code: "KN", en: "Saint Kitts and Nevis", ro: "Sfântul Kitts și Nevis" },
	{ code: "LC", en: "Saint Lucia", ro: "Sfânta Lucia" },
	{ code: "VC", en: "Saint Vincent and the Grenadines", ro: "Sfântul Vincent și Grenadine" },
	{ code: "WS", en: "Samoa", ro: "Samoa" },
	{ code: "SM", en: "San Marino", ro: "San Marino" },
	{ code: "ST", en: "Sao Tome and Principe", ro: "Sao Tome și Principe" },
	{ code: "SA", en: "Saudi Arabia", ro: "Arabia Saudită" },
	{ code: "SN", en: "Senegal", ro: "Senegal" },
	{ code: "RS", en: "Serbia", ro: "Serbia" },
	{ code: "SC", en: "Seychelles", ro: "Seychelles" },
	{ code: "SL", en: "Sierra Leone", ro: "Sierra Leone" },
	{ code: "SG", en: "Singapore", ro: "Singapore" },
	{ code: "SK", en: "Slovakia", ro: "Slovacia" },
	{ code: "SI", en: "Slovenia", ro: "Slovenia" },
	{ code: "SB", en: "Solomon Islands", ro: "Insulele Solomon" },
	{ code: "SO", en: "Somalia", ro: "Somalia" },
	{ code: "ZA", en: "South Africa", ro: "Africa de Sud" },
	{ code: "SS", en: "South Sudan", ro: "Sudanul de Sud" },
	{ code: "ES", en: "Spain", ro: "Spania" },
	{ code: "LK", en: "Sri Lanka", ro: "Sri Lanka" },
	{ code: "SD", en: "Sudan", ro: "Sudan" },
	{ code: "SR", en: "Suriname", ro: "Surinam" },
	{ code: "SZ", en: "Eswatini", ro: "Eswatini" },
	{ code: "SE", en: "Sweden", ro: "Suedia" },
	{ code: "CH", en: "Switzerland", ro: "Elveția" },
	{ code: "SY", en: "Syrian Arab Republic", ro: "Siria" },
	{ code: "TJ", en: "Tajikistan", ro: "Tadjikistan" },
	{ code: "TZ", en: "Tanzania, United Republic of", ro: "Tanzania" },
	{ code: "TH", en: "Thailand", ro: "Thailanda" },
	{ code: "TL", en: "Timor-Leste", ro: "Timorul de Est" },
	{ code: "TG", en: "Togo", ro: "Togo" },
	{ code: "TO", en: "Tonga", ro: "Tonga" },
	{ code: "TT", en: "Trinidad and Tobago", ro: "Trinidad și Tobago" },
	{ code: "TN", en: "Tunisia", ro: "Tunisia" },
	{ code: "TR", en: "Türkiye", ro: "Turcia" },
	{ code: "TM", en: "Turkmenistan", ro: "Turkmenistan" },
	{ code: "TV", en: "Tuvalu", ro: "Tuvalu" },
	{ code: "UG", en: "Uganda", ro: "Uganda" },
	{ code: "UA", en: "Ukraine", ro: "Ucraina" },
	{ code: "AE", en: "United Arab Emirates", ro: "Emiratele Arabe Unite" },
	{ code: "GB", en: "United Kingdom of Great Britain and Northern Ireland", ro: "Regatul Unit" },
	{ code: "US", en: "United States of America", ro: "Statele Unite ale Americii" },
	{ code: "UY", en: "Uruguay", ro: "Uruguay" },
	{ code: "UZ", en: "Uzbekistan", ro: "Uzbekistan" },
	{ code: "VU", en: "Vanuatu", ro: "Vanuatu" },
	{ code: "VE", en: "Venezuela, Bolivarian Republic of", ro: "Venezuela" },
	{ code: "VN", en: "Viet Nam", ro: "Vietnam" },
	{ code: "YE", en: "Yemen", ro: "Yemen" },
	{ code: "ZM", en: "Zambia", ro: "Zambia" },
	{ code: "ZW", en: "Zimbabwe", ro: "Zimbabwe" },
];

function uniqueStrings(values: string[]) {
	return Array.from(new Set(values.filter(Boolean)));
}

function toCountryOption(country: CountryData): CountryOption {
	return {
		...country,
		flagSrc: `/flags/24x24/${country.code.toLowerCase()}.png`,
		keywords: uniqueStrings([country.en, country.ro, country.code, country.code.toLowerCase()])
	};
}

export const countryOptions: CountryOption[] = COUNTRIES.map(toCountryOption);

const countryOptionsByCode = new Map(countryOptions.map((country) => [country.code, country]));

export function normalizeCountryCode(value: string) {
	return value.trim().toUpperCase();
}

export function getCountryOption(value: string) {
	return countryOptionsByCode.get(normalizeCountryCode(value)) ?? null;
}

export function getCountryName(country: CountryOption, locale: CountryLocale) {
	return country[locale] || country.en;
}
